/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myapp.hotel_room_management;

import java.awt.Color;

/**
 *
 * @author Mohammed Al 3mawy
 */
public class Hotel_Room_Management extends javax.swing.JFrame {

    /**
     * Creates new form Hotel_Room_Management
     */
    public Hotel_Room_Management() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        hotel_edt = new javax.swing.JButton();
        hotel_del = new javax.swing.JButton();
        add_hotel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        room_add = new javax.swing.JButton();
        room_edt = new javax.swing.JButton();
        room_del = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(40, 120, 200), null));

        jPanel5.setBackground(new java.awt.Color(40, 120, 200));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("X");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Hotel And Room Management");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)))
        );

        hotel_edt.setBackground(new java.awt.Color(40, 120, 200));
        hotel_edt.setFont(new java.awt.Font("Sitka Small", 0, 18)); // NOI18N
        hotel_edt.setForeground(new java.awt.Color(255, 255, 255));
        hotel_edt.setText("Edit Hotel");
        hotel_edt.setBorderPainted(false);
        hotel_edt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hotel_edtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hotel_edtMouseExited(evt);
            }
        });
        hotel_edt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotel_edtActionPerformed(evt);
            }
        });

        hotel_del.setBackground(new java.awt.Color(40, 120, 200));
        hotel_del.setFont(new java.awt.Font("Sitka Small", 0, 18)); // NOI18N
        hotel_del.setForeground(new java.awt.Color(255, 255, 255));
        hotel_del.setText("- Delete Hotel");
        hotel_del.setBorderPainted(false);
        hotel_del.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hotel_delMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hotel_delMouseExited(evt);
            }
        });
        hotel_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotel_delActionPerformed(evt);
            }
        });

        add_hotel.setBackground(new java.awt.Color(40, 120, 200));
        add_hotel.setFont(new java.awt.Font("Sitka Small", 0, 18)); // NOI18N
        add_hotel.setForeground(new java.awt.Color(255, 255, 255));
        add_hotel.setText("+ Add Hotel");
        add_hotel.setBorderPainted(false);
        add_hotel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                add_hotelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                add_hotelMouseExited(evt);
            }
        });
        add_hotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_hotelActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Hotels manage");

        room_add.setBackground(new java.awt.Color(40, 120, 200));
        room_add.setFont(new java.awt.Font("Sitka Small", 0, 18)); // NOI18N
        room_add.setForeground(new java.awt.Color(255, 255, 255));
        room_add.setText("+ Add Room");
        room_add.setBorderPainted(false);
        room_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                room_addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                room_addMouseExited(evt);
            }
        });
        room_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                room_addActionPerformed(evt);
            }
        });

        room_edt.setBackground(new java.awt.Color(40, 120, 200));
        room_edt.setFont(new java.awt.Font("Sitka Small", 0, 18)); // NOI18N
        room_edt.setForeground(new java.awt.Color(255, 255, 255));
        room_edt.setText("Edit Room");
        room_edt.setBorderPainted(false);
        room_edt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                room_edtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                room_edtMouseExited(evt);
            }
        });

        room_del.setBackground(new java.awt.Color(40, 120, 200));
        room_del.setFont(new java.awt.Font("Sitka Small", 0, 18)); // NOI18N
        room_del.setForeground(new java.awt.Color(255, 255, 255));
        room_del.setText("- Delete Room");
        room_del.setBorderPainted(false);
        room_del.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                room_delMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                room_delMouseExited(evt);
            }
        });
        room_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                room_delActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Rooms manage");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(add_hotel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(hotel_del)
                                .addGap(18, 18, 18)
                                .addComponent(hotel_edt, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(room_add, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(room_del)
                            .addGap(18, 18, 18)
                            .addComponent(room_edt, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_hotel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hotel_del, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hotel_edt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(room_add, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(room_del, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(room_edt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel5MouseClicked

    private void hotel_edtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hotel_edtMouseEntered
        // TODO add your handling code here:
        hotel_edt.setBackground(new Color(40, 120, 200));
    }//GEN-LAST:event_hotel_edtMouseEntered

    private void hotel_edtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hotel_edtMouseExited
        // TODO add your handling code here:
        hotel_edt.setBackground(Color.white);
    }//GEN-LAST:event_hotel_edtMouseExited

    private void hotel_delMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hotel_delMouseEntered
        // TODO add your handling code here:
        hotel_del.setBackground(new Color(40, 120, 200));
    }//GEN-LAST:event_hotel_delMouseEntered

    private void hotel_delMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hotel_delMouseExited
        // TODO add your handling code here:
        hotel_del.setBackground(Color.white);
    }//GEN-LAST:event_hotel_delMouseExited

    private void hotel_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotel_delActionPerformed
        // TODO add your handling code here:
        new Delete_Hotel().setVisible(true);
    }//GEN-LAST:event_hotel_delActionPerformed

    private void add_hotelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_hotelMouseEntered
        // TODO add your handling code here:
        add_hotel.setBackground(new Color(40, 120, 200));
    }//GEN-LAST:event_add_hotelMouseEntered

    private void add_hotelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_hotelMouseExited
        // TODO add your handling code here:
        add_hotel.setBackground(Color.white);
    }//GEN-LAST:event_add_hotelMouseExited

    private void add_hotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_hotelActionPerformed
        // TODO add your handling code here:
        new Add_Hotel().setVisible(true);
    }//GEN-LAST:event_add_hotelActionPerformed

    private void room_addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_room_addMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_room_addMouseEntered

    private void room_addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_room_addMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_room_addMouseExited

    private void room_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_room_addActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_room_addActionPerformed

    private void room_edtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_room_edtMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_room_edtMouseEntered

    private void room_edtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_room_edtMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_room_edtMouseExited

    private void room_delMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_room_delMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_room_delMouseEntered

    private void room_delMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_room_delMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_room_delMouseExited

    private void room_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_room_delActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_room_delActionPerformed

    private void hotel_edtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotel_edtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hotel_edtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hotel_Room_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hotel_Room_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hotel_Room_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hotel_Room_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hotel_Room_Management().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_hotel;
    private javax.swing.JButton hotel_del;
    private javax.swing.JButton hotel_edt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton room_add;
    private javax.swing.JButton room_del;
    private javax.swing.JButton room_edt;
    // End of variables declaration//GEN-END:variables
}
